# Generated by Django 3.0.11 on 2020-12-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordcount', '0003_auto_20201209_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='html',
            field=models.CharField(default=0, max_length=99999999),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
